version: '3.9'

services:

  postgres:
    image: postgres:15

    container_name: telecom_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: telecom_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1

    container_name: airflow

    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./output:/opt/airflow/output

    ports:
      - "8080:8080"

    command: standalone

volumes:
  postgres_data: